config/routes.rb
Rails.application.routes.draw do
  get 'completeds/create'
  get 'completeds/destroy'
  get 'mypage/show'
  root 'top#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get 'users/show'
  resources :posts
  resources :calendars
  resource :users, only: :show
  resource :mypage, only: :show
  resource :top, only: :index
  resources :posts do
    resource :completeds, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :completeds, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def completed_find(post_id)
    completeds.where(post_id: post_id).exists?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの更新・削除はできません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @posts = User.where(user_id: current_user.id)
    @posts = Post.order(start_time: "desc").page(params[:page]).per(8)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_completed.html.erb
<%= link_to '❤️', post_completeds_path(post), method: :delete, remote: true %>

app/views/users/_incompleted.html.erb
<%= link_to '♡', post_completeds_path(post), method: :post, remote: true %>

app/views/users/_post.html.erb
<div class="posts_card h-150 w-60">
  <div class="grid">
    <% @posts.each do |post| %>
      <div class="row row-eq-height">
        <div class="col md-4">
          <div class="card content-card border-dark mb-3">
            <div class="card-body">
              <% if post.image? %>
                <%= image_tag(post.image.url, class:"card-img-top", alt:"Card image cap") %>
              <% else %>
                <img
                  class="card-img-top"
                  src="https://placehold.jp/b5b5ba/3e3d3d/450x340.jpg?text=No%20image"
                  alt="..."
                />
              <% end %>

              <div class="card-body p-4">
                <div class="text-center">
                  <h5 class="fw-bolder"><%= link_to post.title, post %></h5>
                  <p><%= post.start_time.strftime("%Y年%m月%d日") %></p>
                  <p><%= post.user.nickname.present? ? "投稿者： #{post.user.nickname}" : "投稿者：名無しさん" %></p>
                  <p id="post-<%= post.id %>">
                    <% if user_signed_in? && current_user == post.user %>
                      <% if post.completed_by?(current_user) %>
                        <%= render 'users/completed', post: post %>
                      <% else %>
                        <%= render 'users/incompleted', post: post %>
                      <% end %>
                    <% else %>
                      <p>&emsp;
                      </p>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
  <body>
  <%= render "layouts/navber" %>
<br><br><br>


    <header class="bg-warning py-5">
      <div class="container px-1 px-lg-2 my-3">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">朝ごはん投稿一覧</h1>
        </div>
      </div>
    </header>

    <%= render "users/post" %>
    
    <%= paginate @posts %>
    
  
    
    <script src="/scripts."></script>
  </body>
</html>