config/routes.rb
Rails.application.routes.draw do
  get 'completeds/create'
  get 'completeds/destroy'
  get 'mypage/show'
  root 'top#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get 'users/show'
  resources :posts
  resources :calendars
  resource :users, only: :show
  resource :mypage, only: :show
  resource :top, only: :index
  resources :posts do
    resource :completeds, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed.rb
class Completed < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :completeds, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :start_time, presence: true
  validates :title, presence: true
  
  def completed_by?(user)
    completeds.exists?(user_id: user.id)
  end
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :completeds, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def completed_find(post_id)
    completeds.where(post_id: post_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user
  add_flash_types :success, :info, :warning, :danger
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    posts_path
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :destroy, :edit, :update]
  
  def index
    @calendars = Calendar.all
    @calendar = Calendar.new
  end

  def new
    @calendar = Calendar.new
  end

  def show
  end

  def create
    Calendar.create(calendar_params)
    redirect_to calendar_path
  end

  def destroy
    @calendar.destroy!
    redirect_to calendar_path, notice: "削除しました"
  end

  def edit
  end

  def update
    @calendar.update(calendar_params)
    if @blog.update(calendar_params)
      redirect_to calendars_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def set_calendar
    @calendar = Calendar.find(params[:id])
  end

  def calendar_params
    params.require(:calendar).permit(:title, :image, :content, :start_time)
  end
end

app/controllers/completeds_controller.rb
class CompletedsController < ApplicationController
  before_action :post_find

  def create
    current_user.completeds.create!(post_id: params[:post_id])
  end

  def destroy
    current_user.completeds.find_by(post_id: params[:post_id]).destroy!
  end

  private

  def post_find
    @post = Post.find(params[:post_id])
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @posts = Post.where(user_id: current_user.id).order(start_time: "desc").page(params[:page]).per(8)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :ensure_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @posts = Post.where(user_id: current_user.id).includes(:user).all
    @post = Post.new(user_id: @current_user.id)
  end

  def show
  end

  def new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿に失敗しました"
      render "posts/new"
    end
    
  end

  def edit
  end

  def update
    @post.update!(post_params)
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def ensure_user
    unless @post.user == current_user
        redirect_to root_path
    end
  end


  def post_params
    params.require(:post).permit(:title, :image, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @posts = Post.order(start_time: "desc").limit(8)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @posts = User.where(user_id: current_user.id)
    @posts = Post.order(start_time: "desc").page(params[:page]).per(8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/completeds_helper.rb
module CompletedsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/completeds/create.html.erb
<h1>Completeds#create</h1>
<p>Find me in app/views/completeds/create.html.erb</p>

app/views/completeds/create.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("users/completed", post: @post) %>'

app/views/completeds/destroy.html.erb
<h1>Completeds#destroy</h1>
<p>Find me in app/views/completeds/destroy.html.erb</p>

app/views/completeds/destroy.js.erb
document.getElementById('post-<%= @post.id %>').innerHTML = '<%= j render("users/incompleted", post: @post) %>'

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <%= render 'layouts/errors_messages', post: form.object %>
  <div>
    <label><%= form.text_field :title, :placeholder => "タイトル(入力必須)" %></label>
  </div>
  <div class="imagebutton">
    <label class="sized"><%= form.file_field :image, :accept => 'image/*' %></label>
  </div>
  <div class="actions row">
    <p><%= form.text_area :content, :placeholder => "レシピ・メモ(入力自由)" %></p>
  </div>
  <div>
    <%= form.label :start_time, "記録日(入力必須)" %>
    <p><%= form.date_field :start_time %></p>
  </div>
  <div class="formbutton">
    <div class="btns submit">
      <%= form.submit button_value %>
    </div>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render "layouts/navber" %>
<br><br><br><br>

<h1 class="text-center">編集</h1>
<%= render "form", button_value: "更新" %>

app/views/posts/index.html.erb
<%= render "layouts/navber" %>

<br><br><br><br><br><br>

<div class="container">
  <h2 class="section-top"><span class="fas fa-dumbbell" aria-hidden="true"></span>朝ごはん記録</h2>
  <div class="row">
    <div>
      <%= render "form", button_value: "投稿" %>
    </div>
    <div>
      <%= month_calendar events: @posts do |date,posts| %>
        <%= date.day %>
        <% posts.each do |post| %>
          <div class="title-font">
            <%= link_to post.title, post, class:"link" %>
          </div>
          <p id="post-<%= post.id %>">
            <% if user_signed_in? && current_user == post.user %>
              <% if post.completed_by?(current_user) %>
                <%= render 'users/completed', post: post %>
              <% else %>
                <%= render 'users/incompleted', post: post %>
              <% end %>
            <% end %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1><%= link_to "戻る", posts_path %></h1>

app/views/posts/show.html.erb
<%= render "layouts/navber" %>

<br><br><br><br>
<div class="text-center">
  <h1 class="text-center">朝ごはん詳細</h1>
  <p><%= @post.user.nickname.present? ? "投稿者： #{@post.user.nickname}" : "投稿者：名無しさん" %></p>
  <p>タイトル：<%= @post.title %></p>
  <p><%= @post.content %></p>
  <% if @post.image? %>
    <p><%= image_tag @post.image.to_s, size: "380x300" %></p>
  <% end %>
  <p>記録日<%= @post.start_time.strftime("%Y-%m-%d") %></p>
  <td>
    <% if @post.user_id == current_user.id %>
      <%= link_to "編集", edit_post_path(@post) %>
      <%= link_to "削除", @post, method: :delete, data: { confirm: "削除しますか？"} %>
      <p><%= link_to "朝食記録", posts_path %></p>
    <% else %>
      <p><%= link_to "朝食記録", posts_path %></p>
    <% end %>
  </td>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Agency - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.1.0//all."
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700"
      rel="stylesheet"
      type="text/css"
    />

  </head>
  <body id="page-top">
    <%= render "layouts/navber" %>
    <!-- Masthead-->
    <header class="masthead">
      <div class="container">
        <div class="masthead-subheading"></div>
        <div class="masthead-heading text-uppercase">毎日の朝ごはんを<br>記録しよう</div>
        <a class="btn btn-primary btn-xl text-uppercase" href="#services">Breakyとは</a>
      </div>
    </header>
    <!-- Services-->
    <section class="page-section" id="services">
      <div class="container">
        <div class="text-center">
          <h2 class="section-heading text-uppercase">Services</h2>
          <h3 class="section-subheading text-muted"></h3>
        </div>
        <div class="row text-center">
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
            </span>
            <%= image_tag asset_path("humbarger.png") %>
            <br>
            <h4 class="my-3">Share Breakfast</h4>
            <p class="text-muted">朝ごはんを投稿してシェアしよう！</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
            </span>
            <%= image_tag asset_path("riceball1.png") %>
            <h4 class="my-3">Record Breakfast</h4>
            <p class="text-muted">カレンダーに毎日の朝ごはんを記録しよう！</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fas fa-circle fa-stack-2x text-primary"></i>
              <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
            </span>
            <%= image_tag asset_path("heart.jpg") %>
            <h4 class="my-3">Breakfast Completed!</h4>
            <p class="text-muted">完食したらハートボタンを押してカレンダーを<br>❤️いっぱいにしよう！</p>
          </div>
        </div>
      </div>
    </section>
    <!-- Portfolio Grid-->
    <section class="page-section bg-light" id="portfolio">
      <div class="container">
        <div class="text-center">
          <h2 class="section-heading text-uppercase"><%= link_to"朝ごはん一覧",users_path %></h2>
          <h3 class="section-subheading text-muted">Breakfast List</h3>
          <%= render "users/post" %>
        </div>
      </div>
    </section>
  </body>

  <script
    src="https://cdn.delivr.net/npm/bootstrap@5.1.3/dist//bootstrap.bundle.min."
  ></script>

  <script src="/scripts."></script>
</html>