config/routes.rb
Rails.application.routes.draw do
  get 'completeds/create'
  get 'completeds/destroy'
  get 'mypage/show'
  root 'top#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  get 'users/show'
  resources :posts
  resources :calendars
  resource :users, only: :show
  resource :mypage, only: :show
  resource :top, only: :index
  resources :posts do
    resource :completeds, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed.rb
class Completed < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :completeds, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :start_time, presence: true
  validates :title, presence: true
  
  def completed_by?(user)
    completeds.exists?(user_id: user.id)
  end
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :completeds, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def completed_find(post_id)
    completeds.where(post_id: post_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user
  add_flash_types :success, :info, :warning, :danger
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    posts_path
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :destroy, :edit, :update]
  
  def index
    @calendars = Calendar.all
    @calendar = Calendar.new
  end

  def new
    @calendar = Calendar.new
  end

  def show
  end

  def create
    Calendar.create(calendar_params)
    redirect_to calendar_path
  end

  def destroy
    @calendar.destroy!
    redirect_to calendar_path, notice: "削除しました"
  end

  def edit
  end

  def update
    @calendar.update(calendar_params)
    if @blog.update(calendar_params)
      redirect_to calendars_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def set_calendar
    @calendar = Calendar.find(params[:id])
  end

  def calendar_params
    params.require(:calendar).permit(:title, :image, :content, :start_time)
  end
end

app/controllers/completeds_controller.rb
class CompletedsController < ApplicationController
  before_action :post_find

  def create
    current_user.completeds.create!(post_id: params[:post_id])
  end

  def destroy
    current_user.completeds.find_by(post_id: params[:post_id]).destroy!
  end

  private

  def post_find
    @post = Post.find(params[:post_id])
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @posts = Post.where(user_id: current_user.id).order(start_time: "desc").page(params[:page]).per(8)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :ensure_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @posts = Post.where(user_id: current_user.id).includes(:user).all
    @post = Post.new(user_id: @current_user.id)
  end

  def show
  end

  def new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿に失敗しました"
      render "posts/new"
    end
    
  end

  def edit
  end

  def update
    @post.update!(post_params)
    if @post.update(post_params)
      redirect_to @post
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def ensure_user
    unless @post.user == current_user
        redirect_to root_path
    end
  end


  def post_params
    params.require(:post).permit(:title, :image, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @posts = Post.order(start_time: "desc").limit(8)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @posts = User.where(user_id: current_user.id)
    @posts = Post.order(start_time: "desc").page(params[:page]).per(8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/completeds_helper.rb
module CompletedsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors_messages.html.erb
<% if post.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Breakyapp &copy;2022</p></div>
  </footer>
</div>

app/views/layouts/_navber.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="/">Breaky~朝ごはん記録~
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      Menu
      <i class="fas fa-bars ms-1"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item"><a class="nav-link"><%= link_to "アカウント編集", edit_user_registration_path %></a></li>
          <li class="nav-item"><a class="nav-link"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %></a></li>
          <li class="nav-item"><a class="nav-link"><%= link_to "朝ごはん記録・カレンダー", posts_path %></a></li>
          <li class="nav-item"><a class="nav-link"><%= link_to "マイページ", mypage_show_path %></a></li>
          <li class="nav-item"><a class="nav-link"><%= link_to "朝ごはん投稿一覧", users_path %></a></li>
        <% else %>
          <li class="nav-item"><a class="nav-link"><%= link_to "新規登録", new_user_registration_path %></a></li>
          <li class="nav-item"><a class="nav-link"><%= link_to "ログイン", new_user_session_path %></a></li>
          <li class="nav-item"><a class="nav-link"><%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
></script>
<!-- Core theme JS--> <!-- * * * * * * * * * * * * * * * * * * * * * * * * * *
* * * * * * * * * * * * * *--> <!-- * * SB Forms JS * *--> <!-- * * Activate
your form at https://startbootstrap.com/solution/contact-forms * *--> <!-- * *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BreakyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <%= render "layouts/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>